configure.ac: use AC_USE_SYSTEM_EXTENSIONS
We use fcvt and gcvt, both of which are extensions
guarded by GNU_SOURCE. Use AC_USE_SYSTEM_EXTENSIONS
to ensure they're always available.

Fixes a build failure on musl with Clang 15:
```
src/sio/sprint.c:176:15: error: call to undeclared function 'fcvt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                p = (char *)fcvt( num, precision, &decimal_point, is_negative ) ;
src/sio/sprint.c:178:15: error: call to undeclared function 'ecvt'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                p = (char *)ecvt( num, precision+1, &decimal_point, is_negative ) ;
```

And drop a single #define _GNU_SOURCE from signals.c, as it's
preferable to have it consistently defined across the codebase
where possible. We have autotools, so let's use it.